version: 2
jobs:
  build:
    docker:
      - image: circleci/8-stretch-browsers
    steps:
      - checkout
      - run:
          name: Run Tests
          command: npm run test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t mardle/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push marlde/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            deploy/ecs.py --image mardle/$IMAGE_NAME:$TAG" --region $REGION