version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install deps
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t mardle/$IMAGE_NAME:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            if [[ -z "${CIRCLE_TAG}" ]]; then
              docker tag -t mardle/$IMAGE_NAME:latest -t mardle/$IMAGE_NAME:$CIRCLE_TAG
              docker push mardle/$IMAGE_NAME:$TAG
              docker push mardle/$IMAGE_NAME:latest
            else 
              docker push mardle/$IMAGE_NAME:latest
            fi
      # - run:
      #     name: Deploy app to Digital Ocean Server via Docker
      #     command: |
      #       if [[ -z "${CIRCLE_TAG}" ]]; then
      #         deploy/ecs.py --image mardle/$IMAGE_NAME:$CIRCLE_TAG --region $REGION
      #       else
      #         deploy/ecs.py --image mardle/$IMAGE_NAME:latest --region $REGION
      #       fi
